### ISSUE TITLE
Questions on Shepard_CNN

### ISSUE THREAD

**Issue by cuijia1247** [jimmy-ren/vcnn_double-bladed#3]
I am running the Shepard_CNN in my computer (Ubuntu 14.04). There are some problems I found.
1. The 34 line in shepard_sr_x3_demo.m, (images_t = reshape(images_t, size(images_t, 1), size(images_t, 2), 1, size(images_t, 3)), whether the last parameter should be 4? I mean the fifth parameter should be size(images_t, 4). Because when I run the original codes, there will be an error on the reshape function.
2. When I run the script of color_shepard_sr_x3_demo, there will be two images, one is the 'bicubic' another one is the 'ShCNN'. However, the  'ShCNN' one is not as clear as the image in the paper. Should I adjust some parameters?
Thank you.

**Comment by jimmy-ren** [comment]
On business trip. Get back to you soon.

**Comment by jimmy-ren** [comment]
Hi. In shepard_sr_x3_demo.m, I didn't find the reshape you mentioned. What file did you deal with? Did you mean the training script instead of the test script? 
About, "the 'ShCNN' one is not as clear as the image in the paper", did you process the image using the pre-trained weights?

**Comment by sowe2min** [comment]
Hi, firstly,thank you very much for sharing your code. I an running  shepared_inpainting_rgb.m  in win7 system, but there is a error "Undefined function or variable 'prepare_net'" in Line 38  After changing it by 'prepare_sr_net', it works well. So did you make a mistake in here?

**Comment by jimmy-ren** [comment]
Hi. You need run the code from the root folder (the vcnn_double-bladed folder, where you can see folders like 'data', 'cuda', 'applications', etc.), otherwise there will be some path issue. When prompt with some path dialog in matlab, you just press "add to path".

**Comment by sowe2min** [comment]
I get it . Thank you very much! Thank you!
